[project]
name = "elie"
version = "0.1.0"
description = "Explain Like I'm an Expert."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash-bootstrap-components>=2.0.3",
    "dash>=3.0.4",
    "numpy",
]

[project.optional-dependencies]
modal = ["modal>=0.1.0"] 
